name: Generate snake animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *" # Corrigido: Executa à 00:00 e 12:00 UTC

  workflow_dispatch: # Permite disparo manual

  push: # Dispara em pushes para a branch main
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write # Necessário para fazer push para a branch de output
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Gera o arquivo dist/snake.svg com a paleta github-dark
          outputs: dist/snake.svg?palette=github-dark
          # Se quiser ser mais explícito ou adicionar mais arquivos no futuro:
          # outputs: |
          #   dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Branch de destino para o SVG
          build_dir: dist       # Diretório que contém o SVG gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token para autenticação
